# Generated by Django 4.2.29 on 2026-04-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='用例标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='用例描述')),
                ('module', models.CharField(max_length=100, verbose_name='所属模块')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '激活'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('preconditions', models.TextField(blank=True, null=True, verbose_name='前置条件')),
                ('steps', models.JSONField(default=list, verbose_name='测试步骤')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'test_cases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module'], name='test_cases_module_78e396_idx'), models.Index(fields=['priority'], name='test_cases_priorit_c3cda9_idx'), models.Index(fields=['status'], name='test_cases_status_ea5204_idx')],
            },
        ),
    ]
