# Generated by Django 4.2.29 on 2026-04-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='环境名称')),
                ('env_type', models.CharField(choices=[('dev', '开发环境'), ('test', '测试环境'), ('staging', '预发布环境'), ('prod', '生产环境')], max_length=20, verbose_name='环境类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='环境描述')),
                ('host', models.CharField(max_length=200, verbose_name='主机地址')),
                ('port', models.IntegerField(verbose_name='端口号')),
                ('database_name', models.CharField(max_length=100, verbose_name='数据库名称')),
                ('database_user', models.CharField(max_length=100, verbose_name='数据库用户')),
                ('database_password', models.CharField(max_length=200, verbose_name='数据库密码')),
                ('status', models.CharField(choices=[('active', '激活'), ('inactive', '未激活'), ('maintenance', '维护中')], default='active', max_length=20, verbose_name='状态')),
                ('config', models.JSONField(default=dict, verbose_name='环境配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
                'db_table': 'environments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='变量名')),
                ('value', models.TextField(verbose_name='变量值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='变量描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='environments.environment', verbose_name='环境')),
            ],
            options={
                'verbose_name': '环境变量',
                'verbose_name_plural': '环境变量',
                'db_table': 'environment_variables',
                'ordering': ['environment', 'key'],
                'unique_together': {('environment', 'key')},
            },
        ),
        migrations.AddIndex(
            model_name='environment',
            index=models.Index(fields=['env_type'], name='environment_env_typ_6e5cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='environment',
            index=models.Index(fields=['status'], name='environment_status_7abbf9_idx'),
        ),
    ]
