# Generated by Django 4.2.29 on 2026-04-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='计划描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'db_table': 'test_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPlanCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_status', models.CharField(choices=[('not_run', '未执行'), ('passed', '通过'), ('failed', '失败'), ('blocked', '阻塞'), ('skipped', '跳过')], default='not_run', max_length=20, verbose_name='执行状态')),
                ('actual_result', models.TextField(blank=True, null=True, verbose_name='实际结果')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cases', to='test_cases.testcase', verbose_name='测试用例')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cases', to='test_plans.testplan', verbose_name='测试计划')),
            ],
            options={
                'verbose_name': '测试计划用例',
                'verbose_name_plural': '测试计划用例',
                'db_table': 'test_plan_cases',
                'ordering': ['test_plan', 'id'],
                'indexes': [models.Index(fields=['execution_status'], name='test_plan_c_executi_dadf68_idx')],
                'unique_together': {('test_plan', 'test_case')},
            },
        ),
        migrations.AddIndex(
            model_name='testplan',
            index=models.Index(fields=['status'], name='test_plans_status_04bf38_idx'),
        ),
        migrations.AddIndex(
            model_name='testplan',
            index=models.Index(fields=['start_date'], name='test_plans_start_d_010d4e_idx'),
        ),
    ]
