# Generated by Django 4.2.29 on 2026-04-02 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('script_source', models.CharField(choices=[('builtin', '平台内置脚本'), ('upload', '上传脚本'), ('git', 'Git仓库')], max_length=20, verbose_name='脚本来源')),
                ('script_path', models.CharField(max_length=500, verbose_name='脚本路径')),
                ('git_repo', models.URLField(blank=True, null=True, verbose_name='Git仓库地址')),
                ('git_branch', models.CharField(default='main', max_length=100, verbose_name='Git分支')),
                ('execution_command', models.CharField(default='pytest {script} --alluredir=./result', max_length=500, verbose_name='执行命令')),
                ('execution_type', models.CharField(choices=[('manual', '手动执行'), ('scheduled', '定时执行')], default='manual', max_length=20, verbose_name='执行方式')),
                ('cron_expression', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cron表达式')),
                ('retry_count', models.IntegerField(default=0, verbose_name='失败重跑次数')),
                ('timeout', models.IntegerField(default=1800, verbose_name='超时时间(秒)')),
                ('enable_allure', models.BooleanField(default=True, verbose_name='启用Allure报告')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('error', '执行异常'), ('stopped', '已停止')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '自动化任务',
                'verbose_name_plural': '自动化任务',
                'db_table': 'automation_task',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('environment_type', models.CharField(choices=[('test', '测试环境'), ('staging', '预发环境'), ('production', '生产环境'), ('custom', '自定义环境')], max_length=20, verbose_name='环境类型')),
                ('base_url', models.URLField(verbose_name='基础URL')),
                ('variables', models.JSONField(default=dict, verbose_name='环境变量')),
                ('description', models.TextField(blank=True, null=True, verbose_name='环境描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '环境配置',
                'verbose_name_plural': '环境配置',
                'db_table': 'automation_environment',
            },
        ),
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('error', '执行异常'), ('stopped', '已停止')], default='pending', max_length=20, verbose_name='执行状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='执行时长(秒)')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='退出码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.environment', verbose_name='执行环境')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.automationtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '执行历史',
                'verbose_name_plural': '执行历史',
                'db_table': 'automation_execution_history',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('allure', 'Allure报告'), ('junit', 'JUnit报告'), ('html', 'HTML报告')], default='allure', max_length=20, verbose_name='报告类型')),
                ('report_path', models.CharField(max_length=500, verbose_name='报告路径')),
                ('report_url', models.URLField(blank=True, null=True, verbose_name='报告访问URL')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('summary', models.JSONField(default=dict, verbose_name='报告摘要')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='automation.executionhistory', verbose_name='关联执行')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
                'db_table': 'automation_report',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='日志时间')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.executionhistory', verbose_name='关联执行')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'db_table': 'automation_log',
            },
        ),
        migrations.AddField(
            model_name='automationtask',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.environment', verbose_name='执行环境'),
        ),
    ]
