# Generated by Django 4.2.29 on 2026-04-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='docker_container_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='容器名称'),
        ),
        migrations.AddField(
            model_name='environment',
            name='docker_image',
            field=models.CharField(default='python:3.9', max_length=200, verbose_name='Docker镜像'),
        ),
        migrations.AddField(
            model_name='environment',
            name='docker_ports',
            field=models.JSONField(default=list, verbose_name='端口映射'),
        ),
        migrations.AddField(
            model_name='environment',
            name='docker_volumes',
            field=models.JSONField(default=list, verbose_name='卷映射'),
        ),
        migrations.AddField(
            model_name='environment',
            name='executor_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='执行机IP'),
        ),
        migrations.AddField(
            model_name='environment',
            name='executor_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SSH密码'),
        ),
        migrations.AddField(
            model_name='environment',
            name='executor_port',
            field=models.IntegerField(default=22, verbose_name='SSH端口'),
        ),
        migrations.AddField(
            model_name='environment',
            name='executor_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SSH用户名'),
        ),
    ]
