# Generated by Django 4.2.29 on 2026-04-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_environment_docker_container_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='base_url',
        ),
        migrations.AddField(
            model_name='environment',
            name='is_connected',
            field=models.BooleanField(default=False, verbose_name='连接状态'),
        ),
    ]
