# Generated by Django 4.2.29 on 2026-04-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_remove_environment_base_url_environment_is_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationtask',
            name='execution_command',
        ),
    ]
