# Generated by Django 4.2.29 on 2026-04-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_remove_automationtask_execution_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtask',
            name='script_source',
            field=models.CharField(choices=[('git', 'Git仓库')], max_length=20, verbose_name='脚本来源'),
        ),
    ]
