# Generated by Django 4.2.29 on 2026-04-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_alter_automationtask_script_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtask',
            name='git_repo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Git仓库地址'),
        ),
    ]
