# Generated by Django 4.2.29 on 2026-04-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_alter_automationtask_git_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='docker_image',
            field=models.CharField(default='python:3.11', max_length=200, verbose_name='Docker镜像'),
        ),
    ]
