# Generated by Django 4.2.29 on 2026-04-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('query', '查询'), ('execute', '执行'), ('login', '登录'), ('logout', '登出')], max_length=20, verbose_name='操作类型')),
                ('module', models.CharField(choices=[('user', '用户管理'), ('test_case', '测试用例'), ('test_plan', '测试计划'), ('defect', '缺陷管理'), ('api_test', '接口测试'), ('environment', '环境管理'), ('system', '系统管理')], max_length=20, verbose_name='操作模块')),
                ('description', models.CharField(max_length=500, verbose_name='操作描述')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('request_url', models.CharField(max_length=500, verbose_name='请求URL')),
                ('request_params', models.JSONField(default=dict, verbose_name='请求参数')),
                ('request_body', models.JSONField(default=dict, verbose_name='请求体')),
                ('response_status', models.IntegerField(verbose_name='响应状态码')),
                ('response_body', models.JSONField(default=dict, verbose_name='响应体')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('execution_time', models.FloatField(verbose_name='执行时间(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='operation_l_user_id_abc9ca_idx'), models.Index(fields=['action'], name='operation_l_action_23516c_idx'), models.Index(fields=['module'], name='operation_l_module_00a396_idx'), models.Index(fields=['created_at'], name='operation_l_created_3fec78_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], max_length=20, verbose_name='日志级别')),
                ('module', models.CharField(max_length=100, verbose_name='模块')),
                ('message', models.TextField(verbose_name='错误信息')),
                ('traceback', models.TextField(verbose_name='堆栈信息')),
                ('request_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='请求URL')),
                ('request_params', models.JSONField(default=dict, verbose_name='请求参数')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '错误日志',
                'verbose_name_plural': '错误日志',
                'db_table': 'error_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level'], name='error_logs_level_879a02_idx'), models.Index(fields=['module'], name='error_logs_module_bcbb4b_idx'), models.Index(fields=['created_at'], name='error_logs_created_008b9a_idx')],
            },
        ),
    ]
