# Generated by Django 4.2.29 on 2026-04-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_plans', '0001_initial'),
        ('test_cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='缺陷标题')),
                ('description', models.TextField(verbose_name='缺陷描述')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='严重程度')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('new', '新建'), ('assigned', '已分配'), ('in_progress', '处理中'), ('resolved', '已解决'), ('verified', '已验证'), ('closed', '已关闭'), ('reopened', '重新打开')], default='new', max_length=20, verbose_name='状态')),
                ('module', models.CharField(max_length=100, verbose_name='所属模块')),
                ('steps_to_reproduce', models.TextField(verbose_name='复现步骤')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('actual_result', models.TextField(verbose_name='实际结果')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='验证时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defects', to=settings.AUTH_USER_MODEL, verbose_name='分配给')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_defects', to=settings.AUTH_USER_MODEL, verbose_name='报告人')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_defects', to=settings.AUTH_USER_MODEL, verbose_name='解决人')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='test_cases.testcase', verbose_name='关联用例')),
                ('test_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='test_plans.testplan', verbose_name='关联计划')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_defects', to=settings.AUTH_USER_MODEL, verbose_name='验证人')),
            ],
            options={
                'verbose_name': '缺陷',
                'verbose_name_plural': '缺陷',
                'db_table': 'defects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='defects.defect', verbose_name='缺陷')),
            ],
            options={
                'verbose_name': '缺陷评论',
                'verbose_name_plural': '缺陷评论',
                'db_table': 'defect_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['status'], name='defects_status_734a01_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['severity'], name='defects_severit_e0064a_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['priority'], name='defects_priorit_04277e_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['module'], name='defects_module_163683_idx'),
        ),
    ]
