# Generated by Django 4.2.29 on 2026-04-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='环境名称')),
                ('base_url', models.URLField(verbose_name='基础URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='环境描述')),
                ('headers', models.JSONField(default=dict, verbose_name='公共请求头')),
                ('variables', models.JSONField(default=dict, verbose_name='环境变量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_environments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'API环境',
                'verbose_name_plural': 'API环境',
                'db_table': 'api_environments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='用例描述')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=500, verbose_name='请求路径')),
                ('headers', models.JSONField(default=dict, verbose_name='请求头')),
                ('params', models.JSONField(default=dict, verbose_name='请求参数')),
                ('body', models.JSONField(default=dict, verbose_name='请求体')),
                ('expected_status_code', models.IntegerField(default=200, verbose_name='预期状态码')),
                ('expected_response', models.JSONField(default=dict, verbose_name='预期响应')),
                ('assertions', models.JSONField(default=list, verbose_name='断言规则')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='api_test.apienvironment', verbose_name='所属环境')),
            ],
            options={
                'verbose_name': 'API测试用例',
                'verbose_name_plural': 'API测试用例',
                'db_table': 'api_test_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('error', '错误')], default='pending', max_length=20, verbose_name='执行状态')),
                ('request_url', models.CharField(max_length=500, verbose_name='请求URL')),
                ('request_headers', models.JSONField(default=dict, verbose_name='请求头')),
                ('request_body', models.JSONField(default=dict, verbose_name='请求体')),
                ('response_status_code', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('response_headers', models.JSONField(default=dict, verbose_name='响应头')),
                ('response_body', models.JSONField(default=dict, verbose_name='响应体')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='响应时间(ms)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api_test.apitestcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': 'API测试执行记录',
                'verbose_name_plural': 'API测试执行记录',
                'db_table': 'api_test_executions',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['status'], name='api_test_ex_status_4d4603_idx'), models.Index(fields=['executed_at'], name='api_test_ex_execute_87afd0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='apitestcase',
            index=models.Index(fields=['method'], name='api_test_ca_method_1338c5_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestcase',
            index=models.Index(fields=['environment'], name='api_test_ca_environ_9de1d4_idx'),
        ),
    ]
